### ISSUE TITLE
What is "Init With Directory Path"?

### ISSUE THREAD

**Issue by gerchicov-bp** [krishnads/KConfigurableCollectionViewDemo#1]
Contains no images. At least you should add description to the example's functionality

**Comment by krishnads** [comment]
This control is used to fully customize collection view with dynamic number of items in a row. It has two custom constructor methods used for initializing collection view either from array of images or with all Images of a directory. 

Note: If you wnt to init with directory path then you will have to add images first to the directory and you can change the directory name as required in code.
